[package]
name = "mp3-art-tagger"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.3"
reqwest = {version = "0.13.2", features = ["blocking", "json"]}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
urlencoding = "2.1.3"
